### ISSUE TITLE
Invalid line: sub (" instead of ')

### ISSUE THREAD

**Issue by dobin** [Cisco-Talos/mutiny-fuzzer#2]
It appears that sometimes, mutiny_prep creates a wrong .fuzzer line:

Output:
```
Reading in fuzzer data from cap11-0.fuzzer...
	Message #0: 29 bytes outbound
		Subcomponent: 7 additional bytes
		Subcomponent: 7 additional bytes
		Subcomponent: 38 additional bytes
		Subcomponent: 78 additional bytes
	Message #1: 7 bytes inbound
		Subcomponent: 33 additional bytes
		Subcomponent: 51 additional bytes
		Subcomponent: 5 additional bytes
	Message #2: 11 bytes outbound
	Message #3: 6 bytes inbound
	Message #4: 12 bytes outbound
	Message #5: 12 bytes inbound
Invalid line: sub "\xf0x\xda\x00]\x02\xa2\xfd]\x02\x00\x00\x99\x01\x00\x00M\x02\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x03\x00\x00\x001\x02\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x01\x00\x00\x00\x00\x01\x00\x00 \x00\x00\x00\xe7\xbf\xed\x1d\xcci\xb8\x8c\xc08\xb4N\x1a\xd1\xa5\x12\xb7\xb5\x0e\x18C\x1b Xue\xd0\x95)1\x1d{M\xfa\xa8\x13\xc8\x1b\x1b\xe3\x1f\x14\x82F~\xdc@\xc9h*>\xd9\xd6)q^\xb7)\x87~B\x18\x82=z\x94\x0c>\xc6\xc3K\x01\x00i{1>5+\xcc\xaa!\xcf\xbf\x1a\x1c\x7feZ\x8fSD\xbc 1\\\xae\x88T^ \x98t0\x00c\xc3\xa0\xad\x0bH<\x1f\xf9\x13\xa0F\xe2\xa7\xed\x12\x87\xc4w^]\xf4\xf1\x01\xe1`A}'\x0b\x1eX\x95~\xbd:)Y\n\x81>4\xdd\x03\xb5\x86\x96OMA+\x04\xc0\xe0\xd6\x1a\x17\xa7\xef\xad\xff\xe9s`p\xbb\xeb\xef~\x83\x9e\xfeA\x7fA\x1e\xf0\xd6+%|U\xc3\xa1\x85\xaak\xeb\xe4,\xcdL\xc1\xcb\x82\\@\xbe\xdfKF\xc9\x98\xe8\xa7\xfb\x00\x96\xd8\xa8\x97\xe3y\x86\xa2\xeaDd\x11\x89\xe4?l\xce\xac\xf5\x9a\xe1\x9e\x16X\xad(\xc6\xde\xefS\x06\r\xf79\x18CcS@\x12\xc5\xf2\xd7\x88_\x05|\xea\xe7\x9c\xed\n9\x80*:\xcf\xdby\x04\x9eQa|U\xce\x1e\xfe\xb2\xa2]!\x9c\x13\x9d\xad\x99\xd2O9\x19\xfd\x10\xc2\x9e\xe1w\xfcxA\xdf\x9d\xdfC\xf7\x98\xd4\xbd\x14\xf9\xf2\xb7\x8f)\xfdD\xf9j%\xa3]+\xf9\x93A\x8ck\xde\x06\xaf?d\x1f\xda\r\x97\x00\x0b\xcah\xf1\xdd\x0b\xe2?\x8b\x82\xb6w\xfe\x11*\x14,\xebe\x0c&\xb0\xed9\x193\xa9\xabg\xe4\x0f\\;\x99\x06\xefu\xfb\\=\x1cV4\xcf\x1c\x15\x91]\xb1\x8f\xb6\x99\xe0Z\xc4\xb1j\xcc\xaf;Gw\x13?Y\x84\x08C\x12\xf0s-\xb11\x05\x04\xef\xff\xefu=Z-\x89\x0e\xd5X\x93\x0f\xad\x82\x85\xaf\xa6*qMk\xa4\xd3\t\xb3g\x86q\xa7\x80i\x0c\x98I\xd62Ty\xa8\x06\xdeR\xe1\x9c]\x8b\x1e\xf0\xc9}\xc4\xec|\x0e\x93\x08\x00\x88e!\xbe\xf1\x04\x073\xa0\x8c\xaf\xc46\xfbz\xe9\xdai\xbcw\r\x1c9\xe3\x02$\xa9 \xb3\xedCg\xf2\xee\\\xd3+\xc6\xf1^\xa1Ay\xa9hC\x12\x82N\xd2\x18g \x0f| \xf1B\xfbPM\x08vyF\xac\x92\n\x12\x8e\x1d\xca\r\x814A3A2A33\x00\x00\x00\xff\xff"
E: Invalid message data, no message found
Traceback (most recent call last):
  File "./mutiny.py", line 366, in <module>
    fuzzerData.readFromFile(fuzzerFilePath)
  File "/home/dobin/Utils/mutiny-fuzzer/backend/fuzzerdata.py", line 82, in readFromFile
    self.readFromFD(inputFile, quiet=quiet)
  File "/home/dobin/Utils/mutiny-fuzzer/backend/fuzzerdata.py", line 209, in readFromFD
    raise e
RuntimeError: Invalid message data, no message found
```

cap11-0.fuzz:
```
...
outbound '\xfb\x10\xf9\x08\x03\x10\x02\x00\t\x00\x00\x00'
inbound '\xfb\x10\xf9\x08\x03\x10\x02\x00\t\x00\x00\x00'
sub "\xf0x\xda\x00]\x02\xa2\xfd]\x02\x00\x00\x99\x01\x00\x00M\x02\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x03\x00\x00\x001\x02\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x01\x00\x00\x00\x00\x01\x00\x00 \x00\x00\x00\xe7\xbf\xed\x1d\xcci\xb8\x8c\xc08\xb4N\x1a\xd1\xa5\x12\xb7\xb5\x0e\x18C\x1b Xue\xd0\x95)1\x1d{M\xfa\xa8\x13\xc8\x1b\x1b\xe3\x1f\x14\x82F~\xdc@\xc9h*>\xd9\xd6)q^\xb7)\x87~B\x18\x82=z\x94\x0c>\xc6\xc3K\x01\x00i{1>5+\xcc\xaa!\xcf\xbf\x1a\x1c\x7feZ\x8fSD\xbc 1\\\xae\x88T^ \x98t0\x00c\xc3\xa0\xad\x0bH<\x1f\xf9\x13\xa0F\xe2\xa7\xed\x12\x87\xc4w^]\xf4\xf1\x01\xe1`A}'\x0b\x1eX\x95~\xbd:)Y\n\x81>4\xdd\x03\xb5\x86\x96OMA+\x04\xc0\xe0\xd6\x1a\x17\xa7\xef\xad\xff\xe9s`p\xbb\xeb\xef~\x83\x9e\xfeA\x7fA\x1e\xf0\xd6+%|U\xc3\xa1\x85\xaak\xeb\xe4,\xcdL\xc1\xcb\x82\\@\xbe\xdfKF\xc9\x98\xe8\xa7\xfb\x00\x96\xd8\xa8\x97\xe3y\x86\xa2\xeaDd\x11\x89\xe4?l\xce\xac\xf5\x9a\xe1\x9e\x16X\xad(\xc6\xde\xefS\x06\r\xf79\x18CcS@\x12\xc5\xf2\xd7\x88_\x05|\xea\xe7\x9c\xed\n9\x80*:\xcf\xdby\x04\x9eQa|U\xce\x1e\xfe\xb2\xa2]!\x9c\x13\x9d\xad\x99\xd2O9\x19\xfd\x10\xc2\x9e\xe1w\xfcxA\xdf\x9d\xdfC\xf7\x98\xd4\xbd\x14\xf9\xf2\xb7\x8f)\xfdD\xf9j%\xa3]+\xf9\x93A\x8ck\xde\x06\xaf?d\x1f\xda\r\x97\x00\x0b\xcah\xf1\xdd\x0b\xe2?\x8b\x82\xb6w\xfe\x11*\x14,\xebe\x0c&\xb0\xed9\x193\xa9\xabg\xe4\x0f\\;\x99\x06\xefu\xfb\\=\x1cV4\xcf\x1c\x15\x91]\xb1\x8f\xb6\x99\xe0Z\xc4\xb1j\xcc\xaf;Gw\x13?Y\x84\x08C\x12\xf0s-\xb11\x05\x04\xef\xff\xefu=Z-\x89\x0e\xd5X\x93\x0f\xad\x82\x85\xaf\xa6*qMk\xa4\xd3\t\xb3g\x86q\xa7\x80i\x0c\x98I\xd62Ty\xa8\x06\xdeR\xe1\x9c]\x8b\x1e\xf0\xc9}\xc4\xec|\x0e\x93\x08\x00\x88e!\xbe\xf1\x04\x073\xa0\x8c\xaf\xc46\xfbz\xe9\xdai\xbcw\r\x1c9\xe3\x02$\xa9 \xb3\xedCg\xf2\xee\\\xd3+\xc6\xf1^\xa1Ay\xa9hC\x12\x82N\xd2\x18g \x0f| \xf1B\xfbPM\x08vyF\xac\x92\n\x12\x8e\x1d\xca\r\x814A3A2A33\x00\x00\x00\xff\xff"
...
```

As you can see, some lines start with a quote `"` instead of `'`. 

I currently fix it with some sed scripts, but maybe it is possible to just generate valid output?

**Comment by jspadaro** [comment]
Thanks for the feedback, you're right - it appears python's repr() sometimes does double quotes.  I'll try to merge a fix in.

**Comment by dobin** [comment]
I fixed it like this:
```
   # Utility function for setFromSerialized and appendFromSerialized below
    def _extractMessageComponents(self, serializedData):
        firstQuote = serializedData.find("'")
        secondQuote = serializedData.rfind("'")

        if firstQuote == -1 or secondQuote == -1 or firstQuote == secondQuote:
            firstQuote = serializedData.find('"')
            secondQuote = serializedData.rfind('"')

            if firstQuote == -1 or secondQuote == -1 or firstQuote == secondQuote:
                raise RuntimeError("Invalid message data, no message found")
```

But i dont know if `repr()` is most suitable for this task. In FFW, i used pickle files.

**Comment by jspadaro** [comment]
That looks like a good solution, I'll try to merge something like that in, thanks!

We're aware that repr() is really intended for development use.  However, it does provide a human-readable string when used with ASCII data, and it allows for easy tweaks of binary data without a hex editor.  Pickling would unfortunately lose these characteristics and make the .fuzzer files harder to manually edit and copy/paste.

I will close this issue when I merge in your fix.

**Comment by jspadaro** [comment]
I took your fix verbatim and pushed it up to master, as well as fixing the serialization test to catch this issue.  

Thanks!
